### PR TITLE
#133 Fixes

### PR DESCRIPTION
**Pull request by crass45**

### CODE REVIEW

**Comment by Hukoseft** [comment]
Does not follow best practices, has 1 instance of changing the profile points and min selections where the other instance is the correct fix of simply changing which entry is being linked

**Comment by crass45** [comment]
> Does not follow best practices, has 1 instance of changing the profile points and min selections where the other instance is the correct fix of simply changing which entry is being linked


So what is the purpose of having the two-handed Ax twice in the main file?
Wouldn't it be a good practice to eliminate all duplicate wargear in the main file?

**Comment by Hukoseft** [comment]
The purpose of having the 2 entries is so that the one which is automatically included in the wargear is selected by default without having to modify it under every instance where it needs to be not added by default and points incremented.

**Comment by edhorsman** [comment]
The two-handed axe is not an automatic include for the war-gear of the
captain and bo'sun. The model may come with it, but it is an additional 5
point weapon, and is not part of the main war-gear of the model.

**Comment by Hukoseft** [comment]
yes, which is why the issue has not been closed, just this pull request as the issue has not been fixed. I have fixed it on my local copy and will upload it along with the Scouring of the Shire update.

**Comment by edhorsman** [comment]
Awesome!

**Comment by crass45** [comment]
> The purpose of having the 2 entries is so that the one which is automatically included in the wargear is selected by default without having to modify it under every instance where it needs to be not added by default and points incremented.

Wouldn't it be better to have only one entry that can be modified automatically and the optional ones to modify in the profile?

**Comment by Hukoseft** [comment]
No it wouldn't.

1. Creating the entries requires less overhead than modifying it in each individual entry.
2. Linking back to one over the other is a simple fix when errors such as this one occur.
3. Changing the minimum selection doesn't always produce the desired results.

I am currently in the process of adding the new books profiles and legions, I will be going through known bugs while doing so, you can leave them to me.

**Pull request closed without merging**
